# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

WORKDIR /app

# Install build essentials and dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc && rm -rf /var/lib/apt/lists/* \
    && pip install --upgrade pip

# Copy project metadata and install
COPY pyproject.toml uv.lock ./
RUN pip install --no-cache-dir .[cli] python-dotenv

# Copy application code
COPY . .

# Default command
CMD ["python", "main.py"]
